/* automatically generated by rust-bindgen 0.72.1 */

pub const __BITS_PER_LONG: u32 = 64;
pub const __FD_SETSIZE: u32 = 1024;
pub const _IOC_NRBITS: u32 = 8;
pub const _IOC_TYPEBITS: u32 = 8;
pub const _IOC_SIZEBITS: u32 = 14;
pub const _IOC_DIRBITS: u32 = 2;
pub const _IOC_NRMASK: u32 = 255;
pub const _IOC_TYPEMASK: u32 = 255;
pub const _IOC_SIZEMASK: u32 = 16383;
pub const _IOC_DIRMASK: u32 = 3;
pub const _IOC_NRSHIFT: u32 = 0;
pub const _IOC_TYPESHIFT: u32 = 8;
pub const _IOC_SIZESHIFT: u32 = 16;
pub const _IOC_DIRSHIFT: u32 = 30;
pub const _IOC_NONE: u32 = 0;
pub const _IOC_WRITE: u32 = 1;
pub const _IOC_READ: u32 = 2;
pub const IOC_IN: u32 = 1073741824;
pub const IOC_OUT: u32 = 2147483648;
pub const IOC_INOUT: u32 = 3221225472;
pub const IOCSIZE_MASK: u32 = 1073676288;
pub const IOCSIZE_SHIFT: u32 = 16;
pub const OCP_SOURCE_DETAIL_SIZE: u32 = 128;
pub const OCP_MAX_SOURCE_NAME_SIZE: u32 = 120;
pub const OCP_MAX_BUFFER_SIZE: u32 = 4096;
pub const OCP_SVSM_IOCTL_TYPE: u32 = 255;
pub type __s8 = ::std::os::raw::c_schar;
pub type __u8 = ::std::os::raw::c_uchar;
pub type __s16 = ::std::os::raw::c_short;
pub type __u16 = ::std::os::raw::c_ushort;
pub type __s32 = ::std::os::raw::c_int;
pub type __u32 = ::std::os::raw::c_uint;
pub type __s64 = ::std::os::raw::c_longlong;
pub type __u64 = ::std::os::raw::c_ulonglong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __kernel_fd_set {
    pub fds_bits: [::std::os::raw::c_ulong; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __kernel_fd_set"][::std::mem::size_of::<__kernel_fd_set>() - 128usize];
    ["Alignment of __kernel_fd_set"][::std::mem::align_of::<__kernel_fd_set>() - 8usize];
    ["Offset of field: __kernel_fd_set::fds_bits"]
        [::std::mem::offset_of!(__kernel_fd_set, fds_bits) - 0usize];
};
pub type __kernel_sighandler_t =
    ::std::option::Option<unsafe extern "C" fn(arg1: ::std::os::raw::c_int)>;
pub type __kernel_key_t = ::std::os::raw::c_int;
pub type __kernel_mqd_t = ::std::os::raw::c_int;
pub type __kernel_old_uid_t = ::std::os::raw::c_ushort;
pub type __kernel_old_gid_t = ::std::os::raw::c_ushort;
pub type __kernel_old_dev_t = ::std::os::raw::c_ulong;
pub type __kernel_long_t = ::std::os::raw::c_long;
pub type __kernel_ulong_t = ::std::os::raw::c_ulong;
pub type __kernel_ino_t = __kernel_ulong_t;
pub type __kernel_mode_t = ::std::os::raw::c_uint;
pub type __kernel_pid_t = ::std::os::raw::c_int;
pub type __kernel_ipc_pid_t = ::std::os::raw::c_int;
pub type __kernel_uid_t = ::std::os::raw::c_uint;
pub type __kernel_gid_t = ::std::os::raw::c_uint;
pub type __kernel_suseconds_t = __kernel_long_t;
pub type __kernel_daddr_t = ::std::os::raw::c_int;
pub type __kernel_uid32_t = ::std::os::raw::c_uint;
pub type __kernel_gid32_t = ::std::os::raw::c_uint;
pub type __kernel_size_t = __kernel_ulong_t;
pub type __kernel_ssize_t = __kernel_long_t;
pub type __kernel_ptrdiff_t = __kernel_long_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __kernel_fsid_t {
    pub val: [::std::os::raw::c_int; 2usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __kernel_fsid_t"][::std::mem::size_of::<__kernel_fsid_t>() - 8usize];
    ["Alignment of __kernel_fsid_t"][::std::mem::align_of::<__kernel_fsid_t>() - 4usize];
    ["Offset of field: __kernel_fsid_t::val"]
        [::std::mem::offset_of!(__kernel_fsid_t, val) - 0usize];
};
pub type __kernel_off_t = __kernel_long_t;
pub type __kernel_loff_t = ::std::os::raw::c_longlong;
pub type __kernel_old_time_t = __kernel_long_t;
pub type __kernel_time_t = __kernel_long_t;
pub type __kernel_time64_t = ::std::os::raw::c_longlong;
pub type __kernel_clock_t = __kernel_long_t;
pub type __kernel_timer_t = ::std::os::raw::c_int;
pub type __kernel_clockid_t = ::std::os::raw::c_int;
pub type __kernel_caddr_t = *mut ::std::os::raw::c_char;
pub type __kernel_uid16_t = ::std::os::raw::c_ushort;
pub type __kernel_gid16_t = ::std::os::raw::c_ushort;
pub type __s128 = i128;
pub type __u128 = u128;
pub type __le16 = __u16;
pub type __be16 = __u16;
pub type __le32 = __u32;
pub type __be32 = __u32;
pub type __le64 = __u64;
pub type __be64 = __u64;
pub type __sum16 = __u16;
pub type __wsum = __u32;
pub type __poll_t = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ocp_svsm_list_objects {
    pub buf_ptr: __u64,
    pub buf_size: __u32,
    pub buf_size_required: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ocp_svsm_list_objects"][::std::mem::size_of::<ocp_svsm_list_objects>() - 16usize];
    ["Alignment of ocp_svsm_list_objects"]
        [::std::mem::align_of::<ocp_svsm_list_objects>() - 8usize];
    ["Offset of field: ocp_svsm_list_objects::buf_ptr"]
        [::std::mem::offset_of!(ocp_svsm_list_objects, buf_ptr) - 0usize];
    ["Offset of field: ocp_svsm_list_objects::buf_size"]
        [::std::mem::offset_of!(ocp_svsm_list_objects, buf_size) - 8usize];
    ["Offset of field: ocp_svsm_list_objects::buf_size_required"]
        [::std::mem::offset_of!(ocp_svsm_list_objects, buf_size_required) - 12usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ocp_svsm_list_sources {
    pub buf_ptr: __u64,
    pub name_buf_ptr: __u64,
    pub buf_size: __u32,
    pub buf_size_required: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ocp_svsm_list_sources"][::std::mem::size_of::<ocp_svsm_list_sources>() - 24usize];
    ["Alignment of ocp_svsm_list_sources"]
        [::std::mem::align_of::<ocp_svsm_list_sources>() - 8usize];
    ["Offset of field: ocp_svsm_list_sources::buf_ptr"]
        [::std::mem::offset_of!(ocp_svsm_list_sources, buf_ptr) - 0usize];
    ["Offset of field: ocp_svsm_list_sources::name_buf_ptr"]
        [::std::mem::offset_of!(ocp_svsm_list_sources, name_buf_ptr) - 8usize];
    ["Offset of field: ocp_svsm_list_sources::buf_size"]
        [::std::mem::offset_of!(ocp_svsm_list_sources, buf_size) - 16usize];
    ["Offset of field: ocp_svsm_list_sources::buf_size_required"]
        [::std::mem::offset_of!(ocp_svsm_list_sources, buf_size_required) - 20usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ocp_svsm_read_write_source {
    pub buf_ptr: __u64,
    pub name_buf_ptr: __u64,
    pub offset: __u32,
    pub bytes_to_copy: __u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ocp_svsm_read_write_source"]
        [::std::mem::size_of::<ocp_svsm_read_write_source>() - 24usize];
    ["Alignment of ocp_svsm_read_write_source"]
        [::std::mem::align_of::<ocp_svsm_read_write_source>() - 8usize];
    ["Offset of field: ocp_svsm_read_write_source::buf_ptr"]
        [::std::mem::offset_of!(ocp_svsm_read_write_source, buf_ptr) - 0usize];
    ["Offset of field: ocp_svsm_read_write_source::name_buf_ptr"]
        [::std::mem::offset_of!(ocp_svsm_read_write_source, name_buf_ptr) - 8usize];
    ["Offset of field: ocp_svsm_read_write_source::offset"]
        [::std::mem::offset_of!(ocp_svsm_read_write_source, offset) - 16usize];
    ["Offset of field: ocp_svsm_read_write_source::bytes_to_copy"]
        [::std::mem::offset_of!(ocp_svsm_read_write_source, bytes_to_copy) - 20usize];
};
